"""Step 3 Claude call: review rule candidates, add judgment-based ones, and
propose affected regions for flagged geometry.

One call per building. Structured output is forced through a tool definition.
Claude never computes loads; code validates everything it returns
(see validate.py) before the user sees it.

Usage:
    from claude_client.review import review_candidates
    result = review_candidates(building, candidates, cfg)   # needs ANTHROPIC_API_KEY
"""
from __future__ import annotations

import json
from pathlib import Path

from core.candidates import difficult_geometry_flags

ROOT = Path(__file__).resolve().parents[1]

TOOL = {
    "name": "submit_removal_review",
    "description": "Submit the reviewed list of column removal candidates for Alternate Path analysis.",
    "input_schema": {
        "type": "object",
        "properties": {
            "decisions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "location_id": {"type": "string"},
                        "decision": {"type": "string", "enum": ["accept", "reject", "add"]},
                        "reason": {"type": "string", "description": "Plain-language engineering reason"},
                        "clause": {"type": "string", "description": "UFC 4-023-03 clause, e.g. 3-2.9.2.2"},
                        "confidence": {"type": "string", "enum": ["high", "medium", "low"]},
                        "needs_engineer_review": {"type": "boolean"},
                        "affected_region": {
                            "type": "object",
                            "description": "Only for flagged geometry: bays that receive amplified load",
                            "properties": {
                                "levels": {"type": "array", "items": {"type": "string"}},
                                "bays": {"type": "array", "items": {"type": "string"}},
                                "reasoning": {"type": "string"},
                            },
                        },
                    },
                    "required": ["location_id", "decision", "reason", "clause",
                                 "confidence", "needs_engineer_review"],
                },
            },
            "summary": {"type": "string"},
        },
        "required": ["decisions", "summary"],
    },
}


def system_prompt() -> str:
    notes = (ROOT / "docs" / "ufc_notes.md").read_text()
    return (
        "You are assisting a structural engineer with progressive collapse Alternate Path "
        "analysis of a steel frame under UFC 4-023-03 (2009, Change 4). You review column "
        "removal candidates generated by deterministic rules.\n\n"
        "Rules you must follow:\n"
        "- Never reject a candidate marked mandatory=true.\n"
        "- Only add locations that exist in the building's column list.\n"
        "- Add locations only for the judgment-based conditions in 3-2.9.2.2: lightly loaded "
        "adjacent columns, bays with different tributary sizes, members framing in at different "
        "orientations or elevations. Explain the condition you see.\n"
        "- For candidates with geometry flags, propose the affected_region using only bay ids "
        "and level names from the data provided. Otherwise omit affected_region.\n"
        "- Do not compute loads or member capacities.\n"
        "- Cite a clause for every decision. Mark anything uncertain as low confidence and "
        "needs_engineer_review=true.\n\n"
        "Reference notes (the team's summary of the relevant clauses):\n\n" + notes
    )


def building_summary(b: dict) -> dict:
    """Compact view of the building: enough for judgment, small enough to fit."""
    return {
        "grids": b["grids"],
        "levels": b["levels"],
        "stories": [{k: s[k] for k in ("name", "bottom_z", "top_z")} for s in b["stories"]],
        "outlines": b["outlines"],
        "column_locations": sorted({(c["location_id"], c["x"], c["y"]) for c in b["columns"]}),
        "column_sections_by_story": sorted({(c["location_id"], c["story"], c["section"]) for c in b["columns"]}),
        "zones": b.get("zones", []),
    }


def local_neighbourhood(b: dict, location_id: str, radius_m: float = 12.0) -> dict:
    col = next(c for c in b["columns"] if c["location_id"] == location_id)
    p = (col["x"], col["y"])

    def near(q):
        return abs(q[0] - p[0]) <= radius_m and abs(q[1] - p[1]) <= radius_m

    return {
        "bays": [{"id": a["id"], "level": a["level"], "polygon": a["polygon"]}
                 for a in b["bays"] if any(near(v) for v in a["polygon"])],
        "beams": [{"id": bm["id"], "level": bm["level"], "i": bm["i"], "j": bm["j"]}
                  for bm in b["beams"] if near(bm["i"]) or near(bm["j"])],
        "columns": [{"id": c["id"], "x": c["x"], "y": c["y"], "story": c["story"],
                     "lands_on_beam": c.get("lands_on_beam", False)}
                    for c in b["columns"] if near((c["x"], c["y"]))],
    }


def build_user_message(b: dict, candidates: list[dict]) -> str:
    flagged = {}
    for c in candidates:
        f = difficult_geometry_flags(b, c["location_id"])
        if f:
            flagged[c["location_id"]] = {"flags": f, "neighbourhood": local_neighbourhood(b, c["location_id"])}
    payload = {
        "building": building_summary(b),
        "candidates": [{k: c[k] for k in ("location_id", "x", "y", "reasons", "stories", "mandatory")}
                       for c in candidates],
        "flagged_geometry": flagged,
    }
    return ("Review these removal candidates and submit your decisions with the tool.\n\n"
            + json.dumps(payload))


def review_candidates(b: dict, candidates: list[dict], cfg: dict, client=None) -> dict:
    """Call Claude and return the raw tool input (validate it with validate.validate_review)."""
    if client is None:
        import anthropic  # imported lazily so tests don't need the SDK
        client = anthropic.Anthropic()
    resp = client.messages.create(
        model=cfg["claude"]["model"],
        max_tokens=cfg["claude"]["max_tokens"],
        system=system_prompt(),
        tools=[TOOL],
        tool_choice={"type": "tool", "name": TOOL["name"]},
        messages=[{"role": "user", "content": build_user_message(b, candidates)}],
    )
    for block in resp.content:
        if getattr(block, "type", None) == "tool_use":
            return block.input
    raise RuntimeError("Claude did not return a tool_use block")
